//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisBim.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int IdReserva { get; set; }
        public Nullable<int> IdSala { get; set; }
        public string RUT { get; set; }
        public string NombreCliente { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public Nullable<bool> EsPrivado { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<bool> FirmaActa { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Salas Salas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
