//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisBim.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salas
    {
        public Salas()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdSala { get; set; }
        public string NombreSala { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string Detalles { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
